# Generated by Django 4.1.3 on 2022-12-06 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=6)),
                ('bus_type', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=10)),
                ('seats', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='booking_tickets.location', verbose_name='Arrival location')),
                ('departure_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='booking_tickets.location', verbose_name='Departure location')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField(default=django.utils.timezone.now)),
                ('to_time', models.TimeField(default=django.utils.timezone.now)),
                ('travel_time', models.CharField(default=0, max_length=10)),
                ('price', models.FloatField(default=0, max_length=10)),
                ('bus', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='route', to='booking_tickets.bus')),
                ('route', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='route', to='booking_tickets.route')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField(default=0)),
                ('available_ticket', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='available_date', to='booking_tickets.date')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='date',
            name='ticket',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='booking_tickets.ticket'),
        ),
        migrations.AddField(
            model_name='bus',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='booking_tickets.company'),
        ),
    ]
